logging:
  config: classpath:logback/logback-spring-${spring.profiles.active}.xml
# RabbitMQ相关配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    #服务名称修改
    instance-id: ${spring.application.name}-${server.port}
    #访问路径可以显示ip地址
    prefer-ip-address: true
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"